spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.238.66.46:18921/dxxy_e2e?currentSchema=dxxy_e2e
    username: dxxy_e2e
    password: dxxy_2021

server:
  servlet:
    jsp:
      init-parameters:
        development: true #开启jsp页面热部署

mybatis:
  mapper-locations: classpath:com/baizhi/ems/mapper/*.xml #mapper配置文件的位置
  type-aliases-package: com.baizhi.ems.entity
